### ISSUE TITLE
Introductory Statistics => Labs are being collated as independent sections.

### ISSUE THREAD

**Issue by Stackblocks** [Connexions/cnx-rulesets#183] opened 2017-05-02 15:28 UTC
# Scenario

The labs at the end of a chapter are being displayed in their own sections, and are numbered as sections instead of being numbered as `chapter_no`.`lab_no`

# Reproducibility Details

* **Impact area**: Content
*  **User**: n/a
*  **URL / Location**: https://dev00.cnx.org/contents/MBiUQmmY@18.13:iU12wwiG@3/16-Data-Collection-Experiment
* **How many times were you able to reproduce the issue?** n/a

*  **Steps to reproduce**:

1. Open [the book](https://dev00.cnx.org/contents/MBiUQmmY@18.13:kcV4GRqc@8/Preface)
2. Expand the Table of Contents
3. Expand a chapter
4. Click on the one or two sections before `Key Terms`

* **Images or screenshots Included:** Yes  (_attach below_)

1. 
![image](https://cloud.githubusercontent.com/assets/12678235/25625329/da6e468c-2f21-11e7-8c43-d277527e62c5.png)
2.
![image](https://cloud.githubusercontent.com/assets/12678235/25625347/e5f03916-2f21-11e7-9399-a5bc2b02524e.png)

# Environment:

* **Instance**: Dev00
* **OS**: macOS
* **Browser**: Chrome

# Impact

* **Severity**: High
* **Frequency of occurrence**: Common

**Comment by helenemccarron** [comment] 2017-05-17 16:14
![2017-05-17_11-09-32](https://cloud.githubusercontent.com/assets/8514591/26164129/53224490-3af1-11e7-8dca-06bd6558ec04.png)
I believe each Stats Lab is in it's own section by design. The numbering is off because of the Introduction being numbered (I believe that's filed in another issue). The problem here is that Snap Labs aren't numbered at all and lost their title. I will fix that and numbered Stats Labs `chapter_no.lab_no`. The new structure should be: 
`Stats Lab `
`chap#.Lab# Lab title`

**Comment by helenemccarron** [comment] 2017-05-18 16:27
addressed in pr #197

**Comment by helenemccarron** [comment] 2017-05-22 20:48
Per Alana, this format is more desirable than the current pdf display
![2017-05-22_15-47-16](https://cloud.githubusercontent.com/assets/8514591/26327719/07ffce56-3f06-11e7-9c78-9db23e8902bf.png)

**Closed** 2017-05-30 19:37 UTC
Labels: bug
